#!/bin/bash
if [ $1 = "morgan" ] && [ -d "/var/mail/vhosts/wt2-5.ephec-ti.be/morgan/" ]
then
        mutt -f /var/mail/vhosts/wt2-5.ephec-ti.be/morgan/

elif [ $1 = "morgan" ]
then
        echo "morgan has no mail"

elif [ $1 = "martin" ] && [ -d "/var/mail/vhosts/wt2-5.ephec-ti.be/martin/" ]
then
        mutt -f /var/mail/vhosts/wt2-5.ephec-ti.be/martin/

elif [ $1 = "martin" ]
then
        echo "martin has no mail"

elif [ $1 = "olivier" ] && [ -d "/var/mail/vhosts/wt2-5.ephec-ti.be/olivier/" ]
then
        mutt -f /var/mail/vhosts/wt2-5.ephec-ti.be/olivier/

elif [ $1 = "olivier" ]
then
        echo "olivier has no mail"

else
        echo "entrer soit morgan, martin ou olivier"
        echo "permet d'acceder aux boites mails"
fi
