version: '2'

##############################################
##       Docker Services Configuration      ##
##############################################

services:

  soa-ext:
    build: 
      context: ./SOA-ext
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      dmz_net:
          ipv4_address: 172.16.1.2
    volumes:
      - ./SOA-ext/named.conf:/etc/bind/named.conf
      - ./SOA-ext/wt2-5.ephec-ti.be:/etc/bind/wt2-5.ephec-ti.be
      - ./SOA-ext/reverse:/etc/bind/reverse
    container_name: soa-ext
  
  mail:
    build: 
      context: ./Mail
      dockerfile: Dockerfile
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    networks:
      dmz_net:
          ipv4_address: 172.16.1.6
    volumes:
    - ./Mail/logs/maildata:/var/mail
    - ./Mail/logs/mailstate:/var/mail-state
    - ./Mail/logs/maillogs:/var/log/mail
    - ./Mail/config/:/tmp/docker-mailserver/
    env_file:
    - ./Mail/dockerConfig/.env
    - ./Mail/dockerConfig/env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
    hostname: mail
    domainname: wt2-5.ephec-ti.be
    container_name: mail

    



##############################################
##       Docker Networks Configuration      ##
##############################################

networks:

  local_net:
      ipam:
          driver: default
          config:
              - subnet: 172.16.0.0/24
                gateway:  172.16.0.1

  dmz_net:
    ipam:
        driver: default
        config:
            - subnet: 172.16.1.0/24
              gateway: 172.16.1.1
  