version: '2'

##############################################
##       Docker Services Configuration      ##
##############################################

services:

  soa-ext:
    build: 
      context: ./SOA-ext
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      dmz_net:
          ipv4_address: 172.16.1.2
    volumes:
      - ./SOA-ext/named.conf:/etc/bind/named.conf
      - ./SOA-ext/wt2-5.ephec-ti.be:/etc/bind/wt2-5.ephec-ti.be
      - ./SOA-ext/reverse:/etc/bind/reverse
    container_name: soa-ext

  mail:
    build: 
      context: ./Mail
      dockerfile: Dockerfile
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    networks:
      dmz_net:
          ipv4_address: 172.16.1.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    hostname: mail
    container_name: mail

##############################################
##       Docker Networks Configuration      ##
##############################################

networks:

  dmz_net:
    ipam:
        driver: default
        config:
            - subnet: 172.16.1.0/24
              gateway: 172.16.1.1
  