version: '2'

services:

  soa-ext:
    build: 
      context: ./SOA-ext
      dockerfile: Dockerfile
    ports:
      - "53:53"
    networks:
      dmz_net:
          ipv4_address: 172.16.0.11
    volumes:
      - ./SOA-ext/named.conf.local:/etc/bind/named.conf
      - ./SOA-ext/db.wt2-5.ephec-ti.be:/etc/bind/db.wt2-5.ephec-ti.be
    container_name: soa-ext
  
  #Mail-Imap

  #Mail-Smtp



networks:

  local_net:
      ipam:
          driver: default
          config:
              - subnet: 172.16.0.0/29
                gateway:  172.16.0.1

  dmz_net:
    ipam:
        driver: default
        config:
            - subnet: 172.16.0.8/29
              gateway: 172.16.0.9

  