version: '2'

##############################################
##       Docker Services Configuration      ##
##############################################

services:

  soa-ext:
    build: 
      context: ./SOA-ext
      dockerfile: Dockerfile
    ports:
      - "53:53"
    networks:
      dmz_net:
          ipv4_address: 172.16.1.2
    volumes:
      - ./SOA-ext/named.conf:/etc/bind/named.conf
      - ./SOA-ext/wt2-5.ephec-ti.be:/etc/bind/wt2-5.ephec-ti.be
      - ./SOA-ext/194.40.178.51.in-addr.arpa /etc/bind/194.40.178.51.in-addr.arpa
    container_name: soa-ext
  
  #Mail-Imap

  #Mail-Smtp



##############################################
##       Docker Networks Configuration      ##
##############################################

networks:

  local_net:
      ipam:
          driver: default
          config:
              - subnet: 172.16.0.0/24
                gateway:  172.16.0.1

  dmz_net:
    ipam:
        driver: default
        config:
            - subnet: 172.16.1.0/24
              gateway: 172.16.1.1
  