version: '2'

services:

  resolver:
    build: 
      context: ./Resolver
      dockerfile: Dockerfile
    ports:
      - "53:53"
    volumes:
      - ./Resolver/resolv.conf:/etc/bind/named.conf
    container_name: resolver

  #database:
  #  build: 
  #    context: ./Db
  #    dockerfile: Dockerfile
  #  container_name: mysql-db

  #web-local:

  #web-dmz:
  
  