version: '2'

services:

  resolver:
    build: 
      context: ./Resolver
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      local_net:
          ipv4_address: 172.16.0.2
    volumes:
      - ./Resolver/resolv.conf:/etc/bind/named.conf
    container_name: resolver

  database:
    build: 
      context: ./Db
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      local_net:
          ipv4_address: 172.16.0.5
    volumes:
      - ./Db/sql/:/data/
    environment:
      MYSQL_ROOT_PASSWORD: sysadmin
    container_name: mysql-db

  web-dmz:
    build:
      context: ./Web-dmz
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      dmz_net:
          ipv4_address: 172.16.0.10
    volumes:
      - ./Web-dmz/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./Web-dmz/sites/:/usr/local/apache2/htdocs/
    container_name: web-dmz

networks:

  local_net:
      ipam:
          driver: default
          config:
              - subnet: 172.16.0.0/29
                gateway:  172.16.0.1

  dmz_net:
    ipam:
        driver: default
        config:
            - subnet: 172.16.0.8/29
              gateway: 172.16.0.9