#!/bin/bash

#  ---------------------------------------------------------------
# |Installe samba, se connecte et monte un dossier partagé (wt2-5)|
#  ---------------------------------------------------------------

# Colors - code (Red-Blue-Orange-None)
R="\033[0;31m"
B="\033[0;34m"
O="\033[0;33m"
N="\033[0m"

# 2 choix, soit mount le dossier partagé soit umount le dossier partagé
printf "\"1\"=$O Mount un dossier partagé sur le réseau$N\n"
echo "\"2\"=$B Umount un dossier partagé sur le réseau$N\n"
printf "Entrer$O 1$N ou$B 2$N : "
read -s a
printf "\n"

if [ $a = "1" ]
then
sudo apt-get install -y samba samba-common-bin smbclient cifs-utils
sudo mkdir /home/$(whoami)/wt2-5
sudo mount.cifs //192.168.0.99/share /home/$(whoami)/wt2-5 -o user=$(whoami)

elif [ $a = "2" ]
then
sudo umount /home/$(whoami)/wt2-5

else
echo "Erreur !"
fi