#!/bin/bash

#  -----------------------------------------------------------------
# |Installe samba et créer un dossier partagé dans le réseau "wt2-5"|
#  -----------------------------------------------------------------

# Colors - code (Red-Blue-Orange-None)
R="\033[0;31m"
B="\033[0;34m"
O="\033[0;33m"
N="\033[0m"

sudo apt-get install -y samba samba-common-bin smbclient cifs-utils

echo "[share]" >> /etc/samba/smb.conf
echo "path = /home/jarvis/sharedVm" >> /etc/samba/smb.conf
echo "read only = no" >> /etc/samba/smb.conf
echo "public = yes" >> /etc/samba/smb.conf
echo "writable = yes" >> /etc/samba/smb.conf

sudo mkdir /home/$(whoami)/wt2-5

sudo chmod 777 /home/$(whoami)/wt2-5