#!/bin/bash

#  ------------------------------------------
# |Lance le client mail "mutt" pour les users|
#  ------------------------------------------

R="\033[0;31m"
B="\033[0;34m"
O="\033[0;33m"
M="\033[0;95m"
N="\033[0m"

# Nom
printf "\033[0;31mNom : $B"
read -r a
printf "$N"
nom=$(echo "$a" | awk '{print tolower($0)}')

# Prenom
printf "\033[0;31mPrenom : $B"
read -r b
printf "$N"
prenom=$(echo "$b" | awk '{print tolower($0)}')
mail="$nom.$prenom@wt2-5.ephec-ti.be"

# Mail + Connection
printf "Connection au$M serveur mail...$O Démarrage du client mail...$N\n"
printf "Votre nom d'utilisateur est : $R$mail$N\n"
sleep 4
mutt -f imaps://51.178.40.194:993