#!/bin/bash

#  -----------------------------------
# |Get inside docker container (shell)|
#  -----------------------------------

# Colors
R="\033[0;31m"
B="\033[0;34m"
N="\033[0m"

printf "Getting in container $R$1$N by$B shell$N..."
echo ""
sleep 1
docker exec -it $1 sh
