version: '3'

services:

  soa-in:
    build: 
      context: ./SOA
      dockerfile: Dockerfile
    ports:
      - "5353:53" #ATTENTION : dans le résolveur il faudra spécifier : ip_vps_soa-in:5353
    volumes:
      - ./SOA-in/named.conf.local:/etc/bind/named.conf
    container_name: soa-in
  
  soa-ext:
    build: 
      context: ./SOA
      dockerfile: Dockerfile
    ports:
      - "53:53"
    volumes:
      - ./SOA-ext/named.conf.local:/etc/bind/named.conf
    container_name: soa-ext

  #VoIP:

  