version: '2'

##############################################
##       Docker Services Configuration      ##
##############################################

services:
  
  #web-dmz:
  #  build:
  #    context: ./Web-dmz
  #    dockerfile: Dockerfile
  #  ports:
  #    - "80:80"
  #   - "443:443"
  #  networks:
  #    dmz_net:
  #        ipv4_address: 172.16.1.3
  #  volumes:
  #    - ./Web-dmz/www/:/var/www/
  #    - ./Web-dmz/sites-available/:/etc/apache2/sites-available/
  #    - ./Web-dmz/apache2.conf:/etc/apache2/apache2.conf
  #  container_name: web-dmz

  voip:
    build:
      context: ./VoIP
      dockerfile: Dockerfile
    ports:
      - "5060:5060/udp"
      - "19000-20000:19000-20000/udp"
    networks:
      dmz_net:
          ipv4_address: 172.16.1.5
    volumes:
      - ./voIP/config/asterisk/:/etc/asterisk/
    container_name: voip


##############################################
##       Docker Networks Configuration      ##
##############################################

networks:

  local_net:
      ipam:
          driver: default
          config:
              - subnet: 172.16.0.0/24
                gateway:  172.16.0.1

  dmz_net:
    ipam:
        driver: default
        config:
            - subnet: 172.16.1.0/24
              gateway: 172.16.1.1