version: '2'

##############################################
##       Docker Services Configuration      ##
##############################################

services:

  soa-in:
    build: 
      context: ./SOA-in
      dockerfile: Dockerfile
    ports:
      - "53:53"
    networks:
      local_net:
          ipv4_address: 172.16.0.3 
    volumes:
      - ./SOA-in/named.conf:/etc/bind/named.conf
      - ./SOA-in/internal.wt2-5.ephec-ti.be:/etc/bind/internal.wt2-5.ephec-ti.be
      - ./SOA-in/108.40.178.51.in-addr.arpa:/etc/bind/108.40.178.51.in-addr.arpa
    container_name: soa-in
  
  web-local:
    build:
      context: ./Web-local
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      local_net:
          ipv4_address: 172.16.0.4
    volumes:
      - ./Web-local/www/:/var/www/
      - ./Web-local/sites-available/:/etc/apache2/sites-available/
    container_name: web-local

  #VoIP:

##############################################
##       Docker Networks Configuration      ##
##############################################

networks:

  local_net:
      ipam:
          driver: default
          config:
              - subnet: 172.16.0.0/24
                gateway:  172.16.0.1

  dmz_net:
    ipam:
        driver: default
        config:
            - subnet: 172.16.1.0/24
              gateway: 172.16.1.1