version: '2'

services:

  soa-in:
    build: 
      context: ./SOA-in
      dockerfile: Dockerfile
    ports:
      - "53:53"
    networks:
      local_net:
          ipv4_address: 172.16.0.3 
    volumes:
      - ./SOA-in/named.conf.local:/etc/bind/named.conf
      - ./SOA-in/interne.db.wt2-5.ephec-ti.be:/etc/bind/interne.db.wt2-5.ephec-ti.be
    container_name: soa-in
  
  web-local:
    build:
      context: ./Web-local
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      local_net:
          ipv4_address: 172.16.0.4
    volumes:
      - ./Web-local/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./Web-local/sites/:/usr/local/apache2/htdocs/
    container_name: web-local

  #VoIP:


networks:

  local_net:
      ipam:
          driver: default
          config:
              - subnet: 172.16.0.0/29
                gateway:  172.16.0.1

  dmz_net:
    ipam:
        driver: default
        config:
            - subnet: 172.16.0.8/29
              gateway: 172.16.0.9