version: '2'

services:

  user_admin:
    build: .
    networks:
      local_net:
          ipv4_address: 172.16.0.99
    container_name: user_admin


networks:

  local_net:
    external:
      name: vps-morgan_local_net
